"""
Unit tests for the worker Celery App module.
This module covers two main scenarios:
- Happy Path: Verifies the task correctly returns the output generated by the RAG engine.
- Invalid Data: Ensures that an invalid data payload raises a Pydantic ValidationError.
"""
from unittest.mock import patch
import pytest
from pydantic import ValidationError
from src.worker.celery_app import generate_ad_copy_task
from src.api.schemas import GenerateRequest

@patch('src.worker.celery_app.rag_engine')
def test_generate_ad_copy_task_success(mock_task):
    """
    Verifies the task correctly returns the output generated by the RAG engine.
    """
    data = {'keyword': 'fake',
            'promotional_price': 0, 
            'original_price': 0, 
            'product_category': 'fake', 
            'promotional_content': 'fake', 
            'product_name': 'fake'}

    engine = mock_task()

    engine.generate.return_value = 'This is fake copy!'

    output = generate_ad_copy_task(data)

    assert output['ad_copies'][0] == 'This is fake copy!'


def test_generate_ad_copy_task_invalid_data():
    """
    Ensures that an invalid data payload raises a Pydantic ValidationError.
    """
    data = {'keyword': ['invalid', 'type'],
            'promotional_price': 0, 
            'original_price': 0, 
            'product_category': 'fake', 
            'promotional_content': 'fake', 
            'product_name': 'fake'}

    with pytest.raises(ValidationError):
        generate_ad_copy_task(data)
