"""
Unit tests for the worker Celery App module.
This module covers two main scenarios:
- Happy Path: Verifies the task correctly returns the output generated by the RAG engine.
- Invalid Data: Ensures that an invalid data payload raises a Pydantic ValidationError.
"""
from unittest.mock import patch, MagicMock, AsyncMock
import pytest
from pydantic import ValidationError
from src.worker.task import generate_ad_copy_task
from src.api.schemas import GenerateRequest

@patch('src.worker.task.save_task_to_db', new_callable=MagicMock)
@patch('src.worker.task._loop', new_callable=MagicMock)
@patch('src.worker.task.rag_engine')
def test_generate_ad_copy_task_success(mock_rag_engine, mock_loop, mock_save):
    """
    Verifies the task correctly returns the output generated by the RAG engine.
    Unit test only: DB write (save_task_to_db) and event loop are mocked out.
    """
    data = {'keyword': 'fake',
            'promotional_price': 0, 
            'original_price': 0, 
            'product_category': 'fake', 
            'promotional_content': 'fake', 
            'product_name': 'fake'}

    engine = mock_rag_engine()
    engine.generate.return_value = 'This is fake copy!'
    mock_loop.run_until_complete.return_value = None

    output = generate_ad_copy_task(data)

    assert output['ad_copies'][0] == 'This is fake copy!'


def test_generate_ad_copy_task_invalid_data():
    """
    Ensures that an invalid data payload raises a Pydantic ValidationError.
    """
    data = {'keyword': ['invalid', 'type'],
            'promotional_price': 0, 
            'original_price': 0, 
            'product_category': 'fake', 
            'promotional_content': 'fake', 
            'product_name': 'fake'}

    with pytest.raises(ValidationError):
        generate_ad_copy_task(data)
